variables: private/secretfile.yml

web_server:
  bind: 0.0.0.0
  port: 3539
  web_ui: yes

templates:
  global:
    # 10 gigas d'espace disque au minimum
    free_space:
      path: '{? download.defaultPath ?}'
      space: 10000

    # Require at least 15 seeds of any torrent
    #torrent_alive:
    #  min_seeds: 15
    #  reject_for: 2 hours

    disable:
      - private_torrents
    verify_ssl_certificates: no

    transmission:
      host: localhost
      port: 8072
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'
      include_subs: yes
      main_file_only: yes
      ratio: 6
      path: '{? transmission.path ?}'
   
    # Size and seed restrictions require real torrents
    magnets: no
  
  tv:
    thetvdb_lookup: yes
    require_field:
      - tvdb_language
    include:
      - private/series.yml
    transmission:
      #content_filename: "{{series_name}} - {{series_id}} - {{quality}}"
      path: '{? transmission.series_movedone ?}'

    # Push notification Mobile
    notify:
      entries:
        title: "{{series_name}} {{series_id}}"
        message: "{{series_name}} {{series_id}}\n\n{{title}}\n\nSize: {{content_size}}MB\n\nDownloaded by: {{task}}" 
        via:
          - pushbullet:
              api_key: '{? pushbullet.apikey ?}'
      
  imdb_list:
    retry_failed:
      max_retries: 10
    seen: local
    accept_all: yes
    no_entries_ok: yes
    imdb_lookup: yes
    disable:
      - download
      - transmission
      - remember_rejected
      - retry_failed

  movies:
    quality:
      - 720p-1080p
      - hdtv-bluray
    content_size: { min: 1000, max: 15000 }
    seen_movies: strict
    #proper_movies: yes

    # Check for already downloaded manually movies
    exists_movie:
      path:
        - '{? download.defaultPath ?}'
        - '{? movies.pathVF ?}'
        - '{? movies.pathVO ?}'
      type: files
      lookup: imdb
  
    imdb_lookup: yes
    require_field:
      - imdb_id
      - imdb_name
      - imdb_year
      - imdb_url
      - imdb_languages
      - imdb_genres

    set:
      content_filename: "{{ imdb_name|replace('/', '_')|replace(':', ' -') }} ({{ imdb_year }}) - {{ quality }}"

    if:
      - "'french' == (imdb_languages or ['french'])[0]":
          set:
            path: '{? movies.pathVF ?}'
      - "'french' != (imdb_languages or ['french'])[0]":
          set:
            path: '{? movies.pathVO ?}'

    # Push notification Mobile
    notify:
      entries:
        title: "{{imdb_name}} {{imdb_year}} ({{imdb_score}})"
        message: "Genres: {{ imdb_genres|join(', ') }}\n\nTitle: {{title}}\nQuality: {{quality}}\nSize: {{content_size}}MB\n\nDownloaded by: {{task}}"
        via:
          - pushbullet:
              api_key: '{? pushbullet.apikey ?}'
              url: "{% if imdb_url %}{{ imdb_url }}{% endif %}"

  subtitled:
    if:
      - imdb_languages and not 'french' in imdb_languages:
          regexp:
            reject_excluding:
              # Only accept VOSTFR or Multi sub
              - '(?x) [\W_] (?: VOSTFR | MULTISUB | MULTI ) (?:\.|_|\b)'
            from: title
      - tvdb_language and 'french' != tvdb_language:
          regexp:
            reject_excluding:
              # Only accept VOSTFR or Multi sub
              - '(?x) [\W_] (?: VOSTFR | MULTISUB | MULTI ) (?:\.|_|\b)'
            from: title

  movies_watchlist:
    # Download movies in watchlist
    list_match:
      from:
        - movie_list: watchlist

  movies_discover:
    # Don't download movies in watchlist
    list_match:
      remove_on_match: no
      from:
        - movie_list: watchlist
      action: reject

    if:
      - 'imdb_year < now.year - 3': reject
      # Probably a standup comedy.
      - "'comedy' in (imdb_genres or []) and 1 == len(imdb_actors or [])": reject
      # French Movie
      - "'french' == (imdb_languages or ['french'])[0]":
          imdb:
            min_score: 6.4
            min_votes: 150
      # VO Movie
      - "'french' != (imdb_languages or ['french'])[0]":
          imdb:
            min_score: 7.4
            min_votes: 300
      # Restrictions Notes on specific genres
      - "'drama' in (imdb_genres or []) or 'war' in (imdb_genres or []) or 'romance' in (imdb_genres or [])":
          imdb:
            min_score: 7.7
            min_votes: 400
      - "set(['animation', 'family']).issubset(set(imdb_genres or []))":
          imdb:
            min_score: 7.8
            min_votes: 400

  abn_config:
    headers:
      User-Agent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"

  xt_config:
    disable: 
      - torrent_alive
      - remember_rejected
      - private_torrents
    manipulate:
      - url:
          replace:
            regexp: '(details.php\?id=([0-9]+)&hit=1)'
            format: 'download.php?torrent=\2&torrent_pass={? xt.passkey ?}'

tasks:
  
  # Specific Task to download monthly newspaper
  #PressTorrent:
  #  priority: 15
  #  t411:
  #    category: Presse
  #  only_new: yes
  #  disable: 
  #    - inputs
  #    - content_size
  #    - torrent_alive
  #  regexp:
  #    accept:
  #      - '60 millions de consommateurs'
  #      - 'What Hi-Fi'
  #      - 'Marmiton'
  #      - ca m'interesse
  #  exists:
  #    - '{? press.exists ?}'
  #  set:
  #    path: '{? press.path ?}'

  # Search torrent on Dropbox specific synchronised directory
  DropboxTorrent:
    priority: 2
    disable: yes
    disable:
      - seen_movies
      - inputs
      - regexp
      - content_size
      - torrent_alive
    plugin_priority:
      exec: 0
    filesystem:
      path: '{? dropbox.pathTorrent ?}'
      mask: '*.torrent'
      recursive: yes
      retrieve: files
    no_entries_ok: yes
    exec:
      on_output:
        for_accepted: rm "{{location}}"
    accept_all: yes
    set:
      path: '{? dropbox.path ?}'
    # Push notification Mobile
    notify:
      entries:
        title: "Seedbox: {{title}} downloaded\n\n"
        message: ""
        via:
          - pushbullet:
              api_key: '{? pushbullet.apikey ?}'
      

  ###################
  # TV Shows
  ###################

  TV-SHOWS_rss:
    priority: 5
    include:
      - private/input-tvshows-rss.yml
    template: 
      - tv
      - subtitled

  #TV-SHOWS_discover:
  #  priority: 5
  #  include: 
  #    - private/config-t411.yml
  #  discover:
  #    what:
  #      - next_series_episodes: yes
  #    from:
  #      - t411: 
  #          category: Série TV
  #          max_results: 200
  #          terms:
  #            - VOSTFR
  #            - HDrip 1080
  #            - Web-Dl 1080
  #            - TVripHD 1080
  #            - HDrip 720
  #            - Web-DL 720
  #            - TVripHD 720
  #  template:
  #    - tv
  #    - subtitled

  TV-SHOWS_xt:
    priority: 10
    include:
      - private/input-tvshows-xt.yml
    template:
      - tv
      - subtitled
      - xt_config

  TV-SHOWS_abn:
    priority: 10
    include:
      - private/input-tvshows-abn.yml
    template:
      - tv
      - subtitled

  ###################
  # Movies Lists
  ###################
 
  Movies_list_watch_add_from_imdb:
    priority: 8
    imdb_list:
      login: '{? imdb.login ?}'
      password: '{? imdb.password ?}'
      list: watchlist
    list_add:
      - movie_list: watchlist
    template: 
      - no_global # None of the global templates make sense here
      - imdb_list
      
  Movies_list_rating_add_from_imdb:
    priority: 8
    include: 
      - private/input-ratings.yml
    list_add:
      - movie_list: ratinglist
    template: 
      - no_global # None of the global templates make sense here
      - imdb_list

  # Delete already rated movies from IMDB watchlist
  Movies_list_watch_delete_from_imdb:
    priority: 8
    include: 
      - private/input-ratings.yml
    list_remove:
      - movie_list: watchlist
    template: 
      - no_global # None of the global templates make sense here
      - imdb_list

  ###################
  # Movies WatchList
  ###################

  #Movies_watchlist_t411:
  #  priority: 10
  #  t411: 
  #    category: Film
  #    max_results: 200
  #    terms:
  #      - VOSTFR
  #      - HDrip 720
  #      - HDrip 1080
  #  template:
  #    - movies
  #    - subtitled

  Movies_watchlist:
    priority: 10
    max_reruns: 0
    include:
      - private/input-movies-rss.yml
    template:
      - movies
      - subtitled

  Movies_watchlist_xt:
    priority: 10
    max_reruns: 0
    include:
      - private/input-movies-xt.yml
    template:
      - movies
      - movies_watchlist
      - subtitled
      - xt_config

  Movies_watchlist_abn:
    priority: 10
    max_reruns: 0
    include:
      - private/input-movies-abn.yml
    template:
      - movies
      - subtitled
      - abn_config

  ###################
  # Movies Discover
  ###################

 # Movies_discover_t411:
 #   priority: 15
 #   t411: 
 #     category: Film
 #     max_results: 200
 #     terms:
 #       - VOSTFR
 #       - HDrip 720
 #       - HDrip 1080
 #   template:
 #     - movies
 #     - movies_discover
 #     - subtitled

  Movies_discover:
    priority: 15
    max_reruns: 0
    include:
      - private/input-movies-rss.yml
    template:
      - movies
      - movies_discover
      - subtitled

  Movies_discover_xt:
    priority: 15
    max_reruns: 0
    include:
      - private/input-movies-xt.yml
    template:
      - movies
      - movies_discover
      - subtitled
      - xt_config

  Movies_discover_abn:
    priority: 15
    max_reruns: 0
    include:
      - private/input-movies-abn.yml
    template:
      - movies
      - movies_discover
      - subtitled
      - abn_config

  ###################
  # Subtitles
  ###################

  Subtitles:
    template: no_global # None of the global templates make sense here
    priority: 20
    filesystem:
      path: 
        - '{? subtitles.path1 ?}'
        #- '{? subtitles.path2 ?}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    seen: local
    disable:
      - transmission
      - retry_failed
    regexp: 
      reject:
        - '(?x) [\W_] (?: french | VOSTFR | Multi | sample ) (?:\.|_|\b)'
      from: url
    subliminal:
      providers:
        - addic7ed
        - opensubtitles
        - podnapisi
        - tvsubtitles
      authentication:
        addic7ed:
          username: '{? subtitles.addic7ed.username ?}'
          password: '{? subtitles.addic7ed.password ?}'
        opensubtitles:
          username: '{? subtitles.opensubtitles.username ?}'
          password: '{? subtitles.opensubtitles.password ?}'
      languages:
        - fra
      exact_match: yes
  
  StopSeeding:
    clean_transmission:
      port: 8072
      host: localhost
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'
      min_ratio: 4
    template: no_global
    disable: [details]
      

schedules:
    
  #
  # Local
  #
  - tasks: [DropboxTorrent]
    interval:
      minutes: 5

  #Unhandled error in plugin torrent_alive: 'generator' object is not an iterator
  # Subtitles
  #
  #- tasks: [Subtitles]
  #  interval:
  #    hours: 1

  #
  # IMDB Watchlist update
  #
  - tasks: [Movies_list*, StopSeeding]
    schedule:
      hour: 6-23/4
      
  #
  # Tv Shows
  #
  - tasks: [TV-SHOWS_*]
    schedule:
      hour: 6-23/2
      
  #
  # Movies Watchlist
  #
  - tasks: [Movies_watchlist*]
    schedule:
      hour: 6-23/2

  #
  # Movies Discover
  #
  - tasks: [Movies_discover_*]
    schedule:
      hour: 6-23/3
